// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubscribeSourceDto = { id: number, url: string, created_at: number, updated_at: number, confluence_id: number, name: string, content: string, sub_upload?: number, sub_download?: number, sub_total?: number, sub_expire?: number, passive_sync: boolean | null, proxy_server: string | null, proxy_auth: string | null, };
