// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubscribeSourceCreationDto = { confluence_id: number, url: string, name: string, passive_sync: boolean | null, proxy_server: string | null, proxy_auth: string | null, };
