//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::confluence::Entity as Confluence;
pub use super::profile::Entity as Profile;
pub use super::subscribe_source::Entity as SubscribeSource;
