//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subscribe_source")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    #[sea_orm(auto_create_time)]
    pub created_at: DateTime,
    #[sea_orm(auto_update_time)]
    pub updated_at: DateTime,
    pub confluence_id: i32,
    pub name: String,
    pub content: String
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::confluence::Entity",
        from = "Column::ConfluenceId",
        to = "super::confluence::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Confluence,
}

impl Related<super::confluence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Confluence.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
