// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileDto } from './ProfileDto';
import type { SubscribeSourceDto } from './SubscribeSourceDto';

export interface ConfluenceDto {
  id: number;
  template: string;
  creator: string;
  created_at: number;
  updated_at: number;
  mux_content: string;
  subscribe_sources: Array<SubscribeSourceDto>;
  profiles: Array<ProfileDto>;
  name: string;
}
