// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SubscribeSourceDto {
  id: number;
  url: string;
  created_at: number;
  updated_at: number;
  confluence_id: number;
  name: string;
  content: string;
  sub_upload?: number;
  sub_download?: number;
  sub_total?: number;
  sub_expire?: number;
}
