name: cd
on: workflow_dispatch

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest
    environment: DEMO_DEPLOY
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /workspace/outposts
            git reset --hard HEAD
            git pull origin main
            cp -f docker-compose.cd.yaml docker-compose.yaml
            docker compose pull confluence outposts-web
            docker compose up -d --build
