name: ci
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  ORG: outposts-project

jobs:
  build-confluence:
    name: Build Confluence
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 'crates/confluence/Dockerfile'
          push: true
          tags: 'ghcr.io/${{ env.ORG }}/confluence:latest'
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-web:
    name: Build Outposts Web
    runs-on: ubuntu-latest
    environment: BUILD
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create dotenv
        uses: iamsauravsharma/create-dotenv@v2.0.1
        env:
          AUTH_ENDPOINT: ${{ vars.AUTH_ENDPOINT }}
          AUTH_TYPE: ${{ vars.AUTH_TYPE }}
          OUTPOSTS_WEB_AUTH_APPID: ${{ vars.OUTPOSTS_WEB_AUTH_APPID }}
          CONFLUENCE_API_ENDPOINT: ${{ vars.CONFLUENCE_API_ENDPOINT }}
        with:
          input-prefix: '' # Optional (default: '')
          file-path: '.env' # Optional (default : '.env')
          output-prefix: '' # Optional (default: '')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 'apps/outposts-web/Dockerfile'
          push: true
          tags: 'ghcr.io/${{ env.ORG }}/outposts-web:latest'
          cache-from: type=gha
          cache-to: type=gha,mode=max
